import React, { useState } from 'react';
import { FiPrinter, FiX, FiMail, FiMessageCircle, FiCheckCircle, FiRotateCcw } from 'react-icons/fi';
import { sendEmail, sendWhatsApp } from '../utils/messaging';

export default function WarrantyReceiptModal({ isOpen, onClose, deviceData }) {
  const [sending, setSending] = useState({ email: false, whatsapp: false });
  const [sent, setSent] = useState({ email: false, whatsapp: false });

  if (!isOpen || !deviceData) return null;

  const {
    imei,
    customerName,
    mobileNumber,
    email,
    purchaseDate,
    warrantyExpiry,
    extendedWarranty,
    warrantyStatus,
    activationDate,
  } = deviceData;

  const certId = `WBL-WARRANTY-${imei?.slice(-6) || 'XXXXXX'}-${Date.now().toString().slice(-4)}`;
  const warrantyType = extendedWarranty ? 'Extended (2 Years)' : 'Standard (1 Year)';
  const startDate = purchaseDate ? new Date(purchaseDate).toLocaleDateString('en-IN') : 'N/A';
  const endDate = warrantyExpiry ? new Date(warrantyExpiry).toLocaleDateString('en-IN') : 'N/A';
  const activatedOn = activationDate ? new Date(activationDate).toLocaleDateString('en-IN') : new Date().toLocaleDateString('en-IN');

  const brandHeader = `
    <div style="text-align:center; border-bottom:3px solid #4F46E5; padding-bottom:20px; margin-bottom:20px;">
      <div style="font-size:32px; font-weight:bold; color:#4F46E5;">&#128260; Wobble One</div>
      <div style="font-size:18px; color:#666; margin-top:4px;">Official Warranty Certificate</div>
    </div>
  `;

  const certificateBody = `
    <div style="font-family:'Segoe UI',Arial,sans-serif; max-width:600px; margin:0 auto; padding:40px; background:#fff; border:2px solid #4F46E5; border-radius:16px;">
      ${brandHeader}
      <div style="background:#F0FDF4; border:1px solid #22C55E; border-radius:12px; padding:16px; text-align:center; margin-bottom:24px;">
        <span style="font-size:20px; color:#15803D; font-weight:bold;">&#9989; WARRANTY ACTIVE</span>
        <div style="font-size:14px; color:#666; margin-top:4px;">Certificate ID: <strong>${certId}</strong></div>
      </div>
      <table style="width:100%; font-size:15px; line-height:2;">
        <tr><td style="width:40%; font-weight:bold; color:#444;">Customer Name</td><td>${customerName || 'N/A'}</td></tr>
        <tr><td style="font-weight:bold; color:#444;">Mobile Number</td><td>${mobileNumber || 'N/A'}</td></tr>
        <tr><td style="font-weight:bold; color:#444;">IMEI</td><td style="font-family:monospace;">${imei || 'N/A'}</td></tr>
        <tr><td style="font-weight:bold; color:#444;">Purchase Date</td><td>${startDate}</td></tr>
        <tr><td style="font-weight:bold; color:#444;">Activated On</td><td>${activatedOn}</td></tr>
        <tr><td style="font-weight:bold; color:#444;">Warranty Type</td><td><strong>${warrantyType}</strong></td></tr>
        <tr><td style="font-weight:bold; color:#444;">Valid Until</td><td><strong style="color:#4F46E5;">${endDate}</strong></td></tr>
        <tr><td style="font-weight:bold; color:#444;">Status</td><td><span style="color:#22C55E; font-weight:bold;">${warrantyStatus || 'In Warranty'}</span></td></tr>
      </table>
      <div style="margin-top:32px; padding-top:20px; border-top:1px solid #ddd; text-align:center; font-size:13px; color:#888;">
        <p>This certificate is digitally generated by Wobble One CRM.</p>
        <p>For support, contact: support@wobbleone.com | +91 98765 43210</p>
        <p style="margin-top:8px; font-size:11px;">&copy; ${new Date().getFullYear()} Wobble One. All rights reserved.</p>
      </div>
    </div>
  `;

  const handlePrint = () => {
    const printWindow = window.open('', '_blank');
    printWindow.document.write(`
      <html>
        <head>
          <title>Warranty Certificate - ${imei}</title>
          <style>
            body { background:#f5f5f5; padding:20px; font-family: Arial, sans-serif; }
          </style>
        </head>
        <body>
          ${certificateBody}
        </body>
      </html>
    `);
    printWindow.document.close();
    printWindow.focus();
    setTimeout(() => printWindow.print(), 300);
  };

  const handleSendEmail = async () => {
    if (!email) return;
    setSending(prev => ({ ...prev, email: true }));
    const subject = `Your Wobble One Warranty Certificate - ${customerName}`;
    const plainText = `
Dear ${customerName},

Your Wobble One warranty has been successfully activated!

Certificate ID: ${certId}
IMEI: ${imei}
Warranty Type: ${warrantyType}
Valid From: ${startDate}
Valid Until: ${endDate}
Support: +91 98765 43210

Thank you for choosing Wobble One.
    `.trim();
    const result = await sendEmail(email, subject, plainText, {
      certificate_id: certId,
      customer_name: customerName,
      imei: imei,
      warranty_type: warrantyType,
      valid_until: endDate,
    });
    setSending(prev => ({ ...prev, email: false }));
    setSent(prev => ({ ...prev, email: result.success }));
    if (result.success) window.alert('Email sent successfully!');
    else window.alert('Email send failed: ' + (result.error || 'Unknown error'));
  };

  const handleSendWhatsApp = async () => {
    if (!mobileNumber) return;
    setSending(prev => ({ ...prev, whatsapp: true }));
    const message = `*Wobble One Warranty Certificate*\n\nDear ${customerName},\n\nYour warranty is now active!\n\nCert ID: *${certId}*\nIMEI: *${imei}*\nType: *${warrantyType}*\nValid Until: *${endDate}*\n\nThank you for choosing Wobble One!`;
    const result = await sendWhatsApp(mobileNumber, message, certId);
    setSending(prev => ({ ...prev, whatsapp: false }));
    setSent(prev => ({ ...prev, whatsapp: result.success }));
    if (result.success) window.alert('WhatsApp message sent successfully!');
    else window.alert('WhatsApp send failed: ' + (result.error || 'Unknown error'));
  };

  const resetSent = () => setSent({ email: false, whatsapp: false });

  return (
    <div className="fixed inset-0 bg-black/80 backdrop-blur-sm flex items-center justify-center z-50 p-4">
      <div className="bg-white rounded-2xl max-w-2xl w-full max-h-[90vh] overflow-y-auto shadow-2xl">
        {/* Header */}
        <div className="p-6 border-b border-gray-200 flex justify-between items-center sticky top-0 bg-white rounded-t-2xl">
          <div>
            <h2 className="text-2xl font-bold text-gray-900">Warranty Certificate</h2>
            <p className="text-sm text-gray-500">Certificate ID: {certId}</p>
          </div>
          <button onClick={onClose} className="text-gray-400 hover:text-gray-600 p-1 rounded-lg hover:bg-gray-100 transition">
            <FiX size={24} />
          </button>
        </div>

        {/* Certificate Preview */}
        <div className="p-6">
          <div className="border-2 border-indigo-500 rounded-2xl p-6 bg-gradient-to-br from-white to-indigo-50/30">
            <div className="text-center border-b-2 border-indigo-500 pb-4 mb-6">
              <div className="text-3xl font-bold text-indigo-600">&#128260; Wobble One</div>
              <div className="text-lg text-gray-500 mt-1">Official Warranty Certificate</div>
            </div>

            <div className="bg-green-50 border border-green-300 rounded-xl p-4 text-center mb-6">
              <div className="text-xl font-bold text-green-700 flex items-center justify-center gap-2">
                <FiCheckCircle /> WARRANTY ACTIVE
              </div>
              <div className="text-sm text-gray-500 mt-1">Certificate ID: <strong>{certId}</strong></div>
            </div>

            <div className="grid grid-cols-2 gap-4 text-sm">
              <div className="flex flex-col">
                <span className="text-gray-500 text-xs">Customer Name</span>
                <span className="font-semibold text-gray-800">{customerName || 'N/A'}</span>
              </div>
              <div className="flex flex-col">
                <span className="text-gray-500 text-xs">Mobile Number</span>
                <span className="font-semibold text-gray-800">{mobileNumber || 'N/A'}</span>
              </div>
              <div className="flex flex-col">
                <span className="text-gray-500 text-xs">IMEI</span>
                <span className="font-semibold font-mono text-gray-800">{imei || 'N/A'}</span>
              </div>
              <div className="flex flex-col">
                <span className="text-gray-500 text-xs">Purchase Date</span>
                <span className="font-semibold text-gray-800">{startDate}</span>
              </div>
              <div className="flex flex-col">
                <span className="text-gray-500 text-xs">Activated On</span>
                <span className="font-semibold text-gray-800">{activatedOn}</span>
              </div>
              <div className="flex flex-col">
                <span className="text-gray-500 text-xs">Warranty Type</span>
                <span className="font-semibold text-indigo-700">{warrantyType}</span>
              </div>
              <div className="flex flex-col col-span-2">
                <span className="text-gray-500 text-xs">Valid Until</span>
                <span className="font-bold text-lg text-indigo-600">{endDate}</span>
              </div>
              <div className="flex flex-col col-span-2">
                <span className="text-gray-500 text-xs">Status</span>
                <span className="font-bold text-green-600">{warrantyStatus || 'In Warranty'}</span>
              </div>
            </div>

            <div className="mt-6 pt-4 border-t border-gray-200 text-center text-xs text-gray-400">
              <p>This certificate is digitally generated by Wobble One CRM.</p>
              <p>For support: support@wobbleone.com | +91 98765 43210</p>
              <p className="mt-1">&copy; {new Date().getFullYear()} Wobble One. All rights reserved.</p>
            </div>
          </div>
        </div>

        {/* Actions */}
        <div className="p-6 border-t border-gray-200 bg-gray-50 rounded-b-2xl">
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
            <button
              onClick={handlePrint}
              className="flex items-center justify-center gap-2 bg-indigo-600 hover:bg-indigo-700 text-white py-3 px-4 rounded-xl font-medium transition"
            >
              <FiPrinter /> Print / Save PDF
            </button>

            <button
              onClick={handleSendEmail}
              disabled={!email || sending.email || sent.email}
              className={`flex items-center justify-center gap-2 py-3 px-4 rounded-xl font-medium transition ${
                !email
                  ? 'bg-gray-200 text-gray-400 cursor-not-allowed'
                  : sent.email
                  ? 'bg-green-100 text-green-700'
                  : 'bg-blue-600 hover:bg-blue-700 text-white'
              }`}
            >
              {sending.email ? 'Sending...' : sent.email ? <><FiCheckCircle /> Email Sent</> : <><FiMail /> Send Email</>}
            </button>

            <button
              onClick={handleSendWhatsApp}
              disabled={!mobileNumber || sending.whatsapp || sent.whatsapp}
              className={`flex items-center justify-center gap-2 py-3 px-4 rounded-xl font-medium transition ${
                !mobileNumber
                  ? 'bg-gray-200 text-gray-400 cursor-not-allowed'
                  : sent.whatsapp
                  ? 'bg-green-100 text-green-700'
                  : 'bg-green-600 hover:bg-green-700 text-white'
              }`}
            >
              {sending.whatsapp ? 'Sending...' : sent.whatsapp ? <><FiCheckCircle /> WhatsApp Sent</> : <><FiMessageCircle /> Send WhatsApp</>}
            </button>

            {(sent.email || sent.whatsapp) && (
              <button
                onClick={resetSent}
                className="flex items-center justify-center gap-2 bg-gray-200 hover:bg-gray-300 text-gray-700 py-3 px-4 rounded-xl font-medium transition"
              >
                <FiRotateCcw /> Reset
              </button>
            )}
          </div>

          {!email && (
            <p className="text-xs text-amber-600 mt-3 text-center">No email on file. Add customer email to send certificate via email.</p>
          )}
          {!mobileNumber && (
            <p className="text-xs text-amber-600 mt-3 text-center">No mobile number on file. Add customer mobile to send certificate via WhatsApp.</p>
          )}
        </div>
      </div>
    </div>
  );
}

